/**lazy loading */
export const LAZY_LOADING_PAGE_REQUEST = "LAZY_LOADING_PAGE_REQUEST";
/**
 * User Profile image update 
 */
export const PROFILE_IMAGE_REQUEST = "PROFILE_IMAGE_REQUEST";
export const PROFILE_IMAGE_SUCCESS = "PROFILE_IMAGE_SUCCESS";
export const PROFILE_IMAGE_FAILED = "PROFILE_IMAGE_FAILED";

/**
 * user profile image delete
 */

export const PROFILE_IMAGE_DELETE_REQUEST = "PROFILE_IMAGE_DELETE_REQUEST";
export const PROFILE_IMAGE_DELETE_SUCCESS = "PROFILE_IMAGE_DELETE_SUCCESS";
export const PROFILE_IMAGE_DELETE_FAILED = "PROFILE_IMAGE_DELETE_FAILED";

// /**
//  * User profile update
//  */
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED"

/**
 * Change password
 */
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILED =  "CHANGE_PASSWORD_FAILED"


/**
 * Get login user profile details
 */

export const PROFILE_DETAILS_REQUEST = "PROFILE_DETAILS_REQUEST";
export const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS";
export const PROFILE_DETAILS_FAILED = "PROFILE_DETAILS_FAILED";


/**
 * Account deactive
 */

export const ACCOUNT_DEACTIVE_REQUEST = "ACCOUNT_DEACTIVE_REQUEST";
export const ACCOUNT_DEACTIVE_SUCCESS = "ACCOUNT_DEACTIVE_SUCCESS";
export const ACCOUNT_DEACTIVE_FAILED = "ACCOUNT_DEACTIVE_FAILED";


/**
 * get profession
 */
export const GET_PROFESSION_REQUEST = "GET_PROFESSION_REQUEST";
export const GET_PROFESSION_SUCCESS = "GET_PROFESSION_SUCCESS";
export const GET_PROFESSION_FAILED = "GET_PROFESSION_FAILED";
