/**
 * professional profiel details get
 */
/***
 * shope
 */
export const SHOPE_LIST_FAILED = "SHOPE_LIST_FAILED";
export const SHOPE_LIST_REQUEST = "SHOPE_LIST_REQUEST";
export const SHOPE_LIST_SUCCESS = "SHOPE_LIST_SUCCESS";

/**
 * Professional about
 */
export const ABOUT_LIST_FAILED = "ABOUT_LIST_FAILED";
export const ABOUT_LIST_REQUEST = "ABOUT_LIST_REQUEST";
export const ABOUT_LIST_SUCCESS = "ABOUT_LIST_SUCCESS";
/**
 * Professional Reviews
 */
export const REVIEW_LIST_FAILED = "REVIEW_LIST_FAILED";
export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";


/**
 * Follow and Following
 */

export const FOLLOW_FOLLOWING_FAILED = "FOLLOW_FOLLOWING_FAILED";
export const FOLLOW_FOLLOWING_REQUEST = "FOLLOW_FOLLOWING_REQUEST";
export const FOLLOW_FOLLOWING_SUCCESS = "FOLLOW_FOLLOWING_SUCCESS";
export const FOLLOW_FOLLOWING_CLEAR = "FOLLOW_FOLLOWING_CLEAR";

/**
 * Follow and followicng list
 */

export const FOLLOW_FOLLOWING_LIST_FAILED = "FOLLOW_FOLLOWING_LIST_FAILED";
export const FOLLOW_FOLLOWING_LIST_REQUEST = "FOLLOW_FOLLOWING_LIST_REQUEST";
export const FOLLOW_FOLLOWING_LIST_SUCCESS = "FOLLOW_FOLLOWING_LIST_SUCCESS";

/**
 * shop owner project review
 */

export const SHOP_OWNER_REVIEW_LIST_REQUEST = "SHOP_OWNER_REVIEW_LIST_REQUEST";
export const SHOP_OWNER_REVIEW_LIST_FAILED = "SHOP_OWNER_REVIEW_LIST_FAILED";
export const SHOP_OWNER_REVIEW_LIST_SUCCESS = "SHOP_OWNER_REVIEW_LIST_SUCCESS";