/**
 * Projects
 */
export const LIST_PROJECT_FAILED = "LIST_PROJECT_FAILED";
export const LIST_PROJECT_REQUEST = "LIST_PROJECT_REQUEST";
export const LIST_PROJECT_SUCCESS = "LIST_PROJECT_SUCCESS";
/**
 * favourite Projects
 */
export const LIST_FAV_PROJECT_FAILED = "LIST_FAV_PROJECT_FAILED";
export const LIST_FAV_PROJECT_REQUEST = "LIST_FAV_PROJECT_REQUEST";
export const LIST_FAV_PROJECT_SUCCESS = "LIST_FAV_PROJECT_SUCCESS";

/**
 * project details
 */
export const PROJECT_DETAILS_FAILED = "PROJECT_DETAILS_FAILED";
export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";

/* Add to favourite project */
export const FAV_PROJECT_FAILED = "FAV_PROJECT_FAILED";
export const FAV_PROJECT_REQUEST = "FAV_PROJECT_REQUEST";
export const FAV_PROJECT_SUCCESS = "FAV_PROJECT_SUCCESS";

/* send message to owner project */
export const SEND_MESSAGE_TO_OWNER_FAILED = "SEND_MESSAGE_TO_OWNER_FAILED";
export const SEND_MESSAGE_TO_OWNER_REQUEST = "SEND_MESSAGE_TO_OWNER_REQUEST";
export const SEND_MESSAGE_TO_OWNER_SUCCESS = "SEND_MESSAGE_TO_OWNER_SUCCESS";

/*Reviews list */
export const REVIEWS_LIST_REQUEST = "REVIEWS_LIST_REQUEST";
export const REVIEWS_LIST_SUCCESS = "REVIEWS_LIST_SUCCESS";
export const REVIEWS_LIST_FAILED ="REVIEWS_LIST_FAILED";

/* Add comments*/
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS ="ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

/**comment list */
export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAILED = "COMMENT_LIST_FAILED";

/**edit comment */
export const COMMENT_EDIT_REQUEST = "COMMENT_EDIT_REQUEST ";
export const COMMENT_EDIT_SUCCESS = "COMMENT_EDIT_SUCCESS ";
export const COMMENT_EDIT_FAILED = "COMMENT_EDIT_FAILED ";

/**delete comment */
export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAILED = "COMMENT_DELETE_FAILED";

/* Add FAQs*/
export const ADD_FAQS_REQUEST = "ADD_FAQS_REQUEST";
export const ADD_FAQS_SUCCESS = "ADD_FAQS_SUCCESS";
export const ADD_FAQS_FAILED = "ADD_FAQS_FAILED";

/*Faqs list */
export const LIST_FAQS_REQUEST = "LIST_FAQS_REQUEST";
export const LIST_FAQS_SUCCESS ="LIST_FAQS_SUCCESS";
export const LIST_FAQS_FAILED = "LIST_FAQS_FAILED";


/**file preview in project details */

export const FILEPREVIEW_LIST_REQUEST = "FILEPREVIEW_LIST_REQUEST";
export const FILEPREVIEW_LIST_SUCCESS = "FILEPREVIEW_LIST_SUCCESS";
export const FILEPREVIEW_LIST_FAILED = "FILEPREVIEW_LIST_FAILED";


export const SEARCH_VALUES = "SEARCH_VALUES";
export const SEARCH_DROPDOWN_VALUES = "SEARCH_DROPDOWN_VALUES";
