/**
 * Category
 */
export const CATEGORY_LIST_FAILED = "CATEGORY_LIST_FAILED";
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
/* Categories which are used in projects */
export const CATEGORY_PRO_LIST_FAILED = "CATEGORY_PRO_LIST_FAILED";
export const CATEGORY_PRO_LIST_REQUEST = "CATEGORY_PRO_LIST_REQUEST";
export const CATEGORY_PRO_LIST_SUCCESS = "CATEGORY_PRO_LIST_SUCCESS";
/* Sub Categories */
export const CATEGORY_SUB_LIST_FAILED = "CATEGORY_SUB_LIST_FAILED";
export const CATEGORY_SUB_LIST_REQUEST = "CATEGORY_SUB_LIST_REQUEST";
export const CATEGORY_SUB_LIST_SUCCESS = "CATEGORY_SUB_LIST_SUCCESS";
/* Category details */
export const CATEGORY_DETAILS_FAILED = "CATEGORY_DETAILS_FAILED";
export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";
// Category list user wise
export const CATEGORY_LIST_USER_WISE_FAILED = "CATEGORY_LIST_USER_WISE_FAILED";
export const CATEGORY_LIST_USER_WISE_REQUEST = "CATEGORY_LIST_USER_WISE_REQUEST";
export const CATEGORY_LIST_USER_WISE_SUCCESS = "CATEGORY_LIST_USER_WISE_SUCCESS";
