export const CLEAR_STATE = "CLEAR_STATE";
/**
 * Collection
 */
export const LIST_COLLECTION_FAILED = "LIST_COLLECTION_FAILED";
export const LIST_COLLECTION_REQUEST = "LIST_COLLECTION_REQUEST";
export const LIST_COLLECTION_SUCCESS = "LIST_COLLECTION_SUCCESS";
/**
 * Get Collection
 */
export const GET_COLLECTION_FAILED = "GET_COLLECTION_FAILED";
export const GET_COLLECTION_REQUEST = "GET_COLLECTION_REQUEST";
export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
/**
 * Create Collection
 */
export const CREATE_COLLECTION_FAILED = "CREATE_COLLECTION_FAILED";
export const CREATE_COLLECTION_REQUEST = "CREATE_COLLECTION_REQUEST";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
/**
 * Update Collection
 */
export const UPDATE_COLLECTION_FAILED = "UPDATE_COLLECTION_FAILED";
export const UPDATE_COLLECTION_REQUEST = "UPDATE_COLLECTION_REQUEST";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";
/**
 * Delete Collection
 */
export const DELETE_COLLECTION_FAILED = "DELETE_COLLECTION_FAILED";
export const DELETE_COLLECTION_REQUEST = "DELETE_COLLECTION_REQUEST";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
/**
 * add to Collection
 */
export const ADD_TO_COLLECTION_FAILED = "ADD_TO_COLLECTION_FAILED";
export const ADD_TO_COLLECTION_REQUEST = "ADD_TO_COLLECTION_REQUEST";
export const ADD_TO_COLLECTION_SUCCESS = "ADD_TO_COLLECTION_SUCCESS";
